# Use the official PHP 8.3 FPM Alpine image
FROM php:8.3-fpm-alpine

# Set working directory
WORKDIR /var/www/html

# Install system dependencies
RUN apk add --no-cache \
    bash \
    git \
    curl \
    libpng-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
    libzip-dev \
    icu-dev \
    oniguruma-dev \
    freetype-dev \
    zlib-dev \
    gmp-dev \
    tzdata \
    nginx \
    supervisor \
    procps \
    nodejs \
    npm \
    sqlite-dev \
    postgresql-dev \
    postgresql-client \
    mysql-client \
    openssl \
    libxml2-dev \
    libxslt-dev \
    libffi-dev \
    shadow \
    nano \
    build-base \
    autoconf \
    automake \
    m4

RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp

RUN docker-php-ext-install \
    bcmath \
    gd \
    intl \
    mbstring \
    pcntl \
    pdo \
    pdo_mysql \
    pdo_pgsql \
    pdo_sqlite \
    zip \
    gmp \
    exif \
    opcache \
    sockets \
    xml \
    xsl

RUN pecl install redis \
    && docker-php-ext-enable redis

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Copy custom configs
COPY ./docker/nginx/vhost.conf /etc/nginx/http.d/default.conf
COPY ./docker/php/custom-php.ini /usr/local/etc/php/conf.d/custom-php.ini
COPY ./docker/supervisor/supervisord.conf /etc/supervisor/supervisord.conf
COPY ./docker/supervisor/ /etc/supervisor/conf.d/

# Change www-data user ID to 33
RUN usermod -u 33 www-data && \
    groupmod -g 33 www-data

# Switch to non-root user
USER www-data

# Copy application code
COPY --chown=www-data:www-data . /var/www/html

# Copy .env
COPY --chown=www-data:www-data .env.example /var/www/html/.env

# Install Laravel dependencies
RUN composer install --optimize-autoloader --no-scripts

# Expose Nginx ports
EXPOSE 80

# Switch back to root for entrypoint script
USER root

# Copy entrypoint script
COPY ./docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Container healthcheck
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD curl -f http://localhost || exit 1

# Start Supervisord
CMD ["/usr/local/bin/entrypoint.sh"]
