name: Development Workflows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-style-check:
    name: Check Code Style
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Dependencies
        run: composer install --quiet --no-interaction --no-progress --ansi

      - name: Run Pint
        run: ./vendor/bin/pint --test

  static-tests:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install --quiet --no-interaction --no-progress --ansi

      - name: Type Coverage
        run: ./vendor/bin/pest --type-coverage --min=100

      - name: PHPStan
        run: ./vendor/bin/phpstan analyse --no-interaction --error-format=github

  laravel-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo, sqlite, pdo_sqlite,
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --quiet --no-ansi --no-interaction --no-scripts --no-progress

      - name: Create .env
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: touch database/database.sqlite

      - name: Run tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
